### PR TITLE
Allow skip inclusion validate

### PR DESCRIPTION
**Pull request by dieggofaustino**

### CODE REVIEW

**Comment by lucascaton** [comment]
@dieggofaustino I might be missing something here, but wouldn't you have the same behaviour by not adding the flag `validate_inclusion`?

**Comment by lucascaton** [comment]
Hi @dieggofaustino, thanks for your PR.
Just trying to understand what you need: why would you want to ignore this validation?
It'd make things inconsistency, wouldn't it?

**Comment by dieggofaustino** [comment]
@lucascaton in my case, I have an array field on postgres (https://www.postgresql.org/docs/9.1/static/arrays.html), it does fail the inclusion validation, because on `Enumeration.list` is expected to include a string and not an array.
Also, have an issue for disable inclusion validate #55

**Comment by lucascaton** [comment]
Cool, thanks for clarifying @dieggofaustino.

Can you please use the `skip_validation` method that already exists?
Even better: let's rename it to `skip_validations` (plural), does it make sense?

Cheers.

**Comment by dieggofaustino** [comment]
@lucascaton I realized that for this case is not necessary to put the has_enumeration_for. Right?

**Comment by lucascaton** [comment]
@dieggofaustino what do you mean? How would you not have the `has_enumeration_for`? 😄

**Comment by dieggofaustino** [comment]
@lucascaton because the attribute is not a string, but an array. I can still use the enumeration and put his values into array, but without use the has_enumeration_for in the model for the attribute

**Comment by lucascaton** [comment]
@dieggofaustino sorry about the delay in getting back to you.

I got it, so in this case you don't need to skip validations because you won't even need to add `has_enumeration_for`, right?

Cheers.

**Comment by dieggofaustino** [comment]
@lucascaton Yes, that's right. You can close this PR, now. Thank you.

**Pull request closed without merging**
