### PR TITLE
Use humanize enum key for I18n.

### LINKED ISSUE #100: Rails generator should humanize enum key for default I18n value
```
rails generate enumerate_it:enum foo_type bar_baz
      create  config/locales/foo_type.yml
      create  app/enumerations/foo_type.rb
```

```yml
# config/locales/foo_type.yml
en:
  enumerations:
    foo_type:
      bar_baz: 'Bar_baz'
```

I would expect the value for `bar_baz` to be [humanize](https://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-humanize): `'Bar baz'` instead of `'Bar_baz'`.

```ruby
"bar_baz".humanize
# => "Bar baz"
```

### PR DESCRIPTION
**Pull request by masterT**
Fixes #100.

### CODE REVIEW

**Comment by lucascaton** [comment]
Thanks, @masterT! 😃

Would you mind adding a spec covering this scenario?

**Review by lucascaton — COMMENTED** [review]
Thanks, @masterT!

I'm concerned that `humanize` method is part of **ActiveSupport**, isn't it?
This wouldn't work for non-Rails projects 🤔

**Comment by masterT** [comment]
Is the generator only available for Rails project? I thought it was. 🤔

**Comment by lucascaton** [comment]
Ops, you're right. Thanks, @masterT! 😃

**Review by lucascaton — APPROVED** [review]
🙇

**Comment by lucascaton** [comment]
This fix has been included in the latest version of the gem:

- https://rubygems.org/gems/enumerate_it/versions/3.2.2
- https://github.com/lucascaton/enumerate_it/releases/tag/v3.2.2

**Pull request merged**
