### PR TITLE
Add category

### PR DESCRIPTION
**Pull request by dieggofaustino**

### CODE REVIEW

**Comment by lucascaton** [comment]
Hi @dieggofaustino, thanks for submitting this PR. However, I'm not sure if it's really necessary.

What you can do instead is something like the following:

```ruby
# app/enumerations/layout_color.rb
class LayoutColor < EnumerateIt::Base
  associate_values(
    :green,
    :red,
    :yellow,
    :blue
  )

  sort_by :none

  class << self
    def category_a
      [RED, BLUE]
    end

    def category_b
      [GREEN]
    end
  end
end
```

`$ rails console`

```ruby
LayoutColor.category_a
# => ["red", "blue"]

> LayoutColor.category_b
# => ["green"]
```

**Comment by lucascaton** [comment]
Hi @dieggofaustino, does it make sense?

**Comment by dieggofaustino** [comment]
Hi @lucascaton, yes it makes sense.
I started resolving my problem with a solution like your exemple, however it became very repetitive and I wanted something more DRY. Secondly it would be interesting to have a to_a method (for views, forms) and helper methods to identify each category, like associate values.
Your solution is a lot nicer than mine, I can modify the PR to satisfy both worlds. What do you think?

**Comment by lucascaton** [comment]
Hi @dieggofaustino,

I'm not sure if this would be ideal as most of the enumerations wouldn't use it.

As demonstrated in my example, you can declare methods to have categories and in order to DRY you can create these methods dynamically, it's Ruby! 😄

You can also overwrite the `to_a` method, or even create a `EnumerationWithCategory` superclass and then do it:

```ruby
class EnumerationWithCategory < EnumerateIt::Base
  def self.to_a
    # Custom implementation
  end
end

class LayoutColor < EnumerationWithCategory
  associate_values(
    #...
  )

  class << self
    def category_a
      [RED, BLUE]
    end

    # Other categories...
  end
end
```

**Comment by dieggofaustino** [comment]
Ok @lucascaton, I'll use it like this. Thank you for your feedback

**Comment by lucascaton** [comment]
@dieggofaustino no problem! 😄

**Pull request closed without merging**
